# Generated by Django 4.2.6 on 2023-10-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='ChatBot',
        ),
    ]
